# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Create new release
on:
  release:
    types: [created]

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'  # Specify your Node.js version
      - run: npm ci
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.ADO_PAT }}
          registryUrl: https://marketplace.visualstudio.com
