name: Prettier Action

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  prettier:
    name: runner / prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Format code with Prettier
        run: npm run format
      - name: Commit changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: format code with Prettier'
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        if: ${{ github.event_name == 'pull_request' && steps.prettier.outputs.is_formatted == 'true' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format code with Prettier"
          commit-message: ":art: Format code with Prettier"
          body: |
            There appear to be some code formatting errors in ${{ github.sha }}. This pull request
            uses the [Prettier](https://prettier.io/) formatter to fix these issues.
          base: ${{ github.head_ref }}
          branch: actions/prettier
